language: c++
install:
  - sudo apt-get update
  - sudo apt-get install -y graphviz gcovr
script:
  - cd binary-tree-visualizer
  - make
after_script:
  - ./demo
after_success:
  - bash <(curl -s https://codecov.io/bash)
